# Generated by Django 2.2 on 2021-10-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birth',
            name='dateofdeath',
        ),
        migrations.RemoveField(
            model_name='death',
            name='datedeath',
        ),
    ]
