# Generated by Django 2.2 on 2021-10-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211014_0046'),
    ]

    operations = [
        migrations.RunSQL("TRUNCATE TABLE api_country CASCADE")
    ]
