# Generated by Django 2.2 on 2021-10-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211021_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fgdsurveyversion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='householdsurveyversion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='kiisurveyversion',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='lkpfishtechcategory',
            options={'ordering': ('code',), 'verbose_name_plural': 'lkp fish tech categories'},
        ),
        migrations.AlterModelOptions(
            name='monitoringstaff',
            options={'verbose_name_plural': 'monitoring staff'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
    ]
