# Generated by Django 2.2 on 2021-11-06 20:36

import api.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211021_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kii',
            old_name='datacheck',
            new_name='datacheckid',
        ),
        migrations.AddField(
            model_name='habitatrule',
            name='notes',
            field=models.TextField(default='995'),
        ),
        migrations.AddField(
            model_name='speciesrule',
            name='notes',
            field=models.TextField(default='995'),
        ),
        migrations.AlterField(
            model_name='fgd',
            name='npenalty',
            field=models.PositiveSmallIntegerField(default=995, validators=[api.models.base.MaxValueBCValidator(7)]),
        ),
        migrations.AlterField(
            model_name='kii',
            name='kiicode',
            field=models.TextField(default='995'),
        ),
        migrations.AlterField(
            model_name='users',
            name='benefitrank',
            field=models.PositiveSmallIntegerField(default=995, validators=[api.models.base.MinValueBCValidator(1), api.models.base.MaxValueBCValidator(25)]),
        ),
        migrations.AlterField(
            model_name='users',
            name='contributionrank',
            field=models.PositiveSmallIntegerField(default=995, validators=[api.models.base.MinValueBCValidator(1), api.models.base.MaxValueBCValidator(25)]),
        ),
    ]
