# Generated by Django 2.2 on 2021-11-15 15:48

import api.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211106_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='marineorganizationmembership',
            name='days',
            field=models.PositiveIntegerField(default=995, validators=[api.models.base.MaxValueBCValidator(365)]),
        ),
        migrations.AddField(
            model_name='nonmarineorganizationmembership',
            name='days',
            field=models.PositiveIntegerField(default=995, validators=[api.models.base.MaxValueBCValidator(365)]),
        ),
    ]
